# Generated by Django 5.2.11 on 2026-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_number',
            field=models.IntegerField(blank=True),
        ),
    ]
