# Generated by Django 5.2.11 on 2026-03-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermodel_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
