# Generated by Django 5.2.11 on 2026-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermodel_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('conductor', 'Conduct0r'), ('school', 'School')]),
        ),
    ]
