# Generated by Django 5.2.11 on 2026-03-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermodel_mobile_number_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('conductor', 'Conductor'), ('school', 'School')]),
        ),
    ]
