# Generated by Django 5.2.11 on 2026-03-09 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('conductor', 'Conductor'), ('school', 'School')], max_length=20),
        ),
    ]
