# Generated by Django 5.2.11 on 2026-03-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usermodel_mobile_number_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='usermodel',
            unique_together={('username', 'role')},
        ),
    ]
