# Generated by Django 5.2.11 on 2026-03-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usermodel_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='usermodel',
            constraint=models.UniqueConstraint(fields=('username', 'role'), name='unique_username_role'),
        ),
    ]
