# Generated by Django 5.2.11 on 2026-03-17 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_usermodel_unique_together_and_more'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
